apiVersion: v1
kind: Namespace
metadata:
  name: dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"