namePrefix: dev-
commonLabels:
  variant: dev
patchesStrategicMerge:
- ingress.yaml

images:
- name: 794039383763.dkr.ecr.us-east-1.amazonaws.com/lab-flux
  newTag: c250a82ca84ed92bbafd20a417f2e4a6e585b8b2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
