namePrefix: dev-
commonLabels:
  variant: dev
patchesStrategicMerge:
- ingress.yaml

images:
- name: 794039383763.dkr.ecr.us-east-1.amazonaws.com/lab-flux
  newTag: cb13aa0223db0544888b2e57ea6aba1f3bf54313
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
