apiVersion: v1
kind: Service
metadata:
  labels:
    app: aws-example-octodex
  name: aws-example-octodex
spec:
  ports:
    - name: http
      port: 8080
      targetPort: octodex
  selector:
    app: aws-example-octodex
  type: ClusterIP
