apiVersion: v1
kind: Service
metadata:
  labels:
    app: aws-example-octodex
  name: aws-example-octodex
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
  selector:
    app: aws-example-octodex
  type: ClusterIP
