apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: aws-example-octodex
images:
- name: 794039383763.dkr.ecr.us-east-1.amazonaws.com/lab-flux
  newTag: ec5e31617321f2370155c30f6c6804a07853e4a7
