name: Check + CI/CD   

on:
  push:
    paths:
      - app/** 
    branches:
      - master
      - dev
      - trivy

env:
  IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/mytest

jobs:
  ci:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      
    - name: Build and push
      run: |
        docker build \
          -t $IMAGE_ID:${GITHUB_SHA::7} \
          ./app

        # Push image to AWS ECR
        docker push $IMAGE_ID:${GITHUB_SHA::7}

  trivy:
    name: Trivy Test
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE_ID:${GITHUB_SHA::7}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'